### ISSUE TITLE
Example of USB MTP class usage

### ISSUE THREAD

**Issue by ohoc** [STMicroelectronics/stm32_mw_usb_device#13]
Hello,

I have seen that support for the MTP class was added in v2.9.0. That's great!
Unfortunately, there is no documentation or example implementation. Is there something you can share? For example, a usbd_mtp_if.c/h implementation with FatFs as a backing file system?

Thanks in advance.

**Comment by NimaAgm** [comment]
There is MTP Example in this link: STM32Cube_FW_F7_V1.16.2\Projects\STM32F769I_EVAL\Applications\USB_Host\MTP_Standalone
You could find it in STM32Cube repository in your local computer if you have F7 package

**Comment by ohoc** [comment]
Dear Nima,
Thank you for your reply.
Actually, I was refering to the device implementation of the MTP class, not the host. Sorry for the confusion.
Best regards

**Comment by ALABSTM** [comment]
Hi @ohoc,

Please excuse this delayed reply. There is [this](https://github.com/STMicroelectronics/x-cube-azrtos-h7/tree/main/Projects/STM32H735G-DK/Applications/USBX/Ux_Device_PIMA_MTP) application, based on the USBX, however. I hope it addresses your needs.

With regards,
