### ISSUE TITLE
CDC_RNDIS

### ISSUE THREAD

**Issue by sai-sankar-rao** [STMicroelectronics/stm32_mw_usb_device#17]
**Caution**
CDC_RNDIS is not detecting as network adapter in device manger 

**Describe the set-up**
 * STM32L072CZY3TR.
 * STM32CubeIDE Version: 1.14.1.

**Additional context**
 I am using STM32L072CZY3TR controller and integrated CDC_RNDIS as device in the controller, it got complied without any issues and after flashing it in controller, I landed with this issue "disabled in the network settings".
even trying to enable not resolving the issue. (I hope something with Endpoints but not sure)

please help me clear this issue

**Screenshots**
![Screenshot 2024-06-10 124821](https://github.com/STMicroelectronics/stm32_mw_usb_device/assets/172247823/d3d330db-d0ee-4758-98e1-3cc75e3be7d0)
![image](https://github.com/STMicroelectronics/stm32_mw_usb_device/assets/172247823/00fc91fd-e566-4165-801f-f8203599911f)

**Comment by ALABSTM** [comment]
Hi @sai-sankar-rao,

Thank you for your question. However, this support channel is dedicated to issues found in the software items published within this repository. Support requests like this one shall be rather submitted to the [ST Community](https://community.st.com/t5/stm32-mcus/ct-p/stm32-mcus).

Please allow me to close this thread. Thank for your comprehension.

With regards,
