### ISSUE TITLE
Cube packages come with old USB middleware versions

### ISSUE THREAD

**Issue by fronders** [STMicroelectronics/stm32_mw_usb_device#6]
I've noticed most of STM32 Cube packages come with USB Device library of v2.7.1 which dates back to August 2020. What is the roadmap/plan on integrating latest USB middleware libs, when will 2.10 become part of Cube packages (like L4, F4)? Especially interested in composite devices, since previously had to do this myself, thanks

**Comment by ALABSTM** [comment]
Hi @fronders,

Indeed, some firmware packages do not integrate the latest library version yet. Actually, there is currently no plan for these packages to integrate any newer versions. However, as you noticed, you can **easily integrate** these newer versions into your project by yourself, as they are **backward compatible**.

In the meanwhile, please allow me to close this issue. We can easily reopen it, should there be any updates regarding this point. Thank you for your comprehension.

With regards,
