### ISSUE TITLE
License incompatible with GPLed libraries

### ISSUE THREAD

**Issue by StefanBruens** [STMicroelectronics/stm32_mw_usb_device#9]
The MW licenses factually disallows any linking to GPLed third party library and distributing the resultant binary.

The MW license poses several restrictions on usage, while the GPL (any version) disallows restricting usage.

The [CubeMX software page](https://www.st.com/en/embedded-software/stm32cubef1.html) says "Free user-friendly license terms". This is obviously not correct.

**Comment by ALABSTM** [comment]
Hi @StefanBruens,

Thank you for this feedback. Although a GPL- or a BSD-like license would have been less restrictive, the use of this SLA0044 license is a choice made by STMicroelectronics based on a number of considerations.

On the other hand, I also note the relative flexibility offered by this SLA0044 license in terms of modification and redistribution as source code or binary file.

Please allow me to close this thread. Thank you for your comprehension and thank you again for your feedback.

With regards,

**Comment by StefanBruens** [comment]
If you don't want to change the license, that's your choice.

But you should be honest and remove the "Free user-friendly" statement, and add a warning the SLA0044 is incompatible with the GPL.

You are putting developers at risk, users and supporters of genuine STM parts. Anyone who provides binaries containing code covered by the SLA0044 and GPLed code is susceptible to legal actions.
